version: "3.8"

services:
  jupyter:
    build: .
    container_name: house-price-prediction
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
    command: >
      jupyter notebook
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --NotebookApp.token=''
      --NotebookApp.password=''

